
spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: local
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
# 운영환경
server:
  port: 8089